canton {
  participants {
    sandbox {
      storage {
        type = postgres
        config {
          dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "postgres"
            portNumber = "5432"
            databaseName = "escrow"
            user = "escrow"
            password = "escrow"
          }
        }
      }
      admin-api {
        port = 6866
        address = 0.0.0.0
      }
      ledger-api {
        port = 6865
        address = 0.0.0.0
      }
      http-ledger-api {
        port = 7575
        address = 0.0.0.0
      }
    }
  }
}
