server {
    listen 8080;

    location /bank/ {
        proxy_pass http://bank-api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /buyer/ {
        proxy_pass http://buyer-api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /seller/ {
        proxy_pass http://seller-api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        return 200 'gateway-ok';
    }
}
