name: daml-script
id: daml-script-3.4.11
version: 3.4.11
exposed: True
exposed-modules: Daml.Script.Internal.Questions.Crypto.Text Daml.Script Daml.Script.Internal.Questions.Crypto Daml.Script.Internal.Questions.Query Daml.Script.Internal.Questions.Submit.Error Daml.Script.Internal.Questions.PartyManagement Daml.Script.Internal.Questions.TransactionTree Daml.Script.Internal.Questions Daml.Script.Internal.Questions.Commands Daml.Script.Internal.LowLevel Daml.Script.Internal.Questions.Time Daml.Script.Internal.Questions.Util Daml.Script.Internal Daml.Script.Internal.Questions.Testing Daml.Script.Internal.Questions.Exceptions Daml.Script.Internal.Questions.Packages Daml.Script.Internal.Questions.Submit Daml.Script.Internal.Free Daml.Script.Internal.Questions.UserManagement
import-dirs: ${pkgroot}/daml-script-3.4.11-fe2e0175af21ba46d48cda3614edb9e30f2bc6972c20eb1d09666fa81703aa2e
library-dirs: ${pkgroot}/daml-script-3.4.11-fe2e0175af21ba46d48cda3614edb9e30f2bc6972c20eb1d09666fa81703aa2e
data-dir: ${pkgroot}/daml-script-3.4.11-fe2e0175af21ba46d48cda3614edb9e30f2bc6972c20eb1d09666fa81703aa2e
depends: daml-prim daml-stdlib-3.4.11
