apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: escrow-ingress
  namespace: bank
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    # High-Assurance TLS (Public)
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.global-static-ip-name: "escrow-gateway-ip-dev"
    # High-Assurance mTLS (Internal Origin)
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "bank/bank-api-mtls-secret"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
spec:
  tls:
  - hosts:
    - api.vdatacloudai.com
    secretName: escrow-gateway-tls-secret
  rules:
  - host: api.vdatacloudai.com
    http:
      paths:
      - path: /bank/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: bank-api
            port:
              number: 443
      - path: /buyer/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: buyer-api-cross
            port:
              number: 443
      - path: /seller/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: seller-api-cross
            port:
              number: 443
---
# Cross-Namespace Links (mTLS Port)
apiVersion: v1
kind: Service
metadata:
  name: buyer-api-cross
  namespace: bank
spec:
  type: ExternalName
  externalName: buyer-api.buyer.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: seller-api-cross
  namespace: bank
spec:
  type: ExternalName
  externalName: seller-api.seller.svc.cluster.local
