apiVersion: v1
kind: Namespace
metadata:
  name: bank
  labels:
    env: dev
    participant: bank
---
apiVersion: v1
kind: Namespace
metadata:
  name: depositor
  labels:
    env: dev
    participant: depositor
---
apiVersion: v1
kind: Namespace
metadata:
  name: beneficiary
  labels:
    env: dev
    participant: beneficiary
