/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover auth settings for an email
         * @description Return the configured Identity Provider (IdP) or bypass settings for a given email address
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Discover Auth Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.DiscoverAuthRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description provider not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user identity
         * @description Retrieve the authenticated user's profile and resolved Canton Party ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.UserIdentity"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cryptographic challenge nonce
         * @description Generate and persist a single-use UUID challenge string for wallet authentication handshakes (replays prevented)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/wallet/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify wallet signature and obtain token
         * @description Authoritatively validates the cryptographic signature of the nonce and returns a secure JWT platform session token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Verify Wallet Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.VerifyWalletRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description invalid signature or nonce */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description token generation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get application config settings
         * @description Retrieve all persistent database configurations for the authenticated user context
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        /**
         * Save config settings
         * @description Set or update a persistent database configuration key-value pair for the current authenticated user context
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Save Config Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.SaveConfigRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List drafts for user
         * @description Get all active or completed draft versions where the user is an initiator or invitee counterparty
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["services.DraftEscrow"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        /**
         * Save new draft agreement
         * @description Create a new persistent contract proposal draft in the Postgres database, initialized as DRAFT state
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Save Draft Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.SaveDraftRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["services.DraftEscrow"];
                    };
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{draftID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get draft by ID
         * @description Retrieve the latest version details of a specific contract draft by its ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Draft ID */
                    draftID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["services.DraftEscrow"];
                    };
                };
                /** @description draft not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{draftID}/amend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose draft amendment
         * @description Propose a modified version of a contract draft, creating a new history item in Postgres and bumping the version
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Draft ID */
                    draftID: string;
                };
                cookie?: never;
            };
            /** @description Amend Draft Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.AmendDraftRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["services.DraftEscrow"];
                    };
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{draftID}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve contract draft
         * @description Approve the current latest version of a contract draft. If both counterparty roles approve, state shifts to RATIFIED.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Draft ID */
                    draftID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description failed to approve */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{draftID}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote draft to active ledger escrow
         * @description Bilateral promote a RATIFIED contract draft onto the Canton ledger as a proposed or active Escrow contract
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Draft ID */
                    draftID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns status and ledgerId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description draft not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description promotion failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active escrows
         * @description Get a list of active Escrow contracts from the Canton ledger associated with the user's role/party
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.EscrowContract"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        /**
         * Propose a new escrow agreement
         * @description Create a draft agreement on the Canton ledger awaiting counterparty acceptance
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Propose Escrow Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.ProposeEscrowRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.EscrowProposal"];
                    };
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description proposal failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{escrowID}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate funded escrow
         * @description Acknowledge funding and activate the escrow contract for condition validation
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    escrowID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description activated contract ID */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description activation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{escrowID}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm escrow conditions
         * @description Bilateral or mediator counter-signing confirming conditions of the active escrow are met
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    escrowID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description confirmation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{escrowID}/disburse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disburse active milestone funds
         * @description Release funds for the active milestone to the beneficiary upon successful condition confirmation
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    escrowID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description disbursement failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{escrowID}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Raise escrow dispute
         * @description Initiates dispute state on the active escrow, halting normal milestone disbursement and routing to the mediator
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    escrowID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description dispute failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{escrowID}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize dispute settlement
         * @description Finalize a ratified dispute settlement split on the ledger
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    escrowID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description finalized contract ID */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description finalization failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{escrowID}/fund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fund active escrow
         * @description Approve and authorize transfer of stablecoins from depositor custody vault holding into the escrow contract
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    escrowID: string;
                };
                cookie?: never;
            };
            /** @description Fund Escrow Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.FundEscrowRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description funding failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{escrowID}/propose-settlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose dispute settlement split
         * @description Create a settlement payout distribution proposal (buyer refund amount vs seller disburse amount)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    escrowID: string;
                };
                cookie?: never;
            };
            /** @description Propose Settlement Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.ProposeSettlementRequest"];
                };
            };
            responses: {
                /** @description proposed settlement ID */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description proposal failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{escrowID}/ratify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ratify dispute settlement split
         * @description Bilateral ratify the proposed dispute payout split
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    escrowID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ratified contract ID */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description ratification failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get escrow details
         * @description Retrieve the full contract state details of a specific escrow by its ledger ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.EscrowContract"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description escrow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{id}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get escrow event history
         * @description Retrieve structured audit log events (creation, funding, activate, confirm, etc.) for a specific escrow contract
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["services.EscrowLifecycleMetadata"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system health and uptime
         * @description Check uptime, CPU/Memory stats and status of internal services
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enriched participant identities
         * @description Get a directory of all Canton identities enriched with displays names, affiliation, titles, and emails from Postgres database
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.UserIdentity"][];
                    };
                };
                /** @description internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest agreement documents via AI
         * @description Accept uploaded PDF/images, perform AI extraction of escrow terms and amount, and return structured metadata
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Agreement contract PDF or image files
                         */
                        agreement: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["services.IngestResult"];
                    };
                };
                /** @description missing or invalid files */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description ingestion failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description ingest service unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ledger invitations
         * @description Fetch a list of active invitations awaiting claimant countersignatures from the Canton ledger
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.EscrowInvitation"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        /**
         * Create off-chain invitation
         * @description Propose an off-chain contract draft for a counterparty email invite, establishing a zero-latency initiation tunnel
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create Invitation Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.CreateInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["services.DraftEscrow"];
                    };
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/token/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get invitation by token
         * @description Resolve a specific Canton ledger invitation details by token hash
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invitation Token Hash */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.EscrowInvitation"];
                    };
                };
                /** @description invitation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/token/{token}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim invitation token
         * @description Claim an invitation token hash, linking the off-chain draft with the claimant user and initiating verification
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invitation Token Hash */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid or expired token */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system performance metrics
         * @description Retrieve real-time metrics including total volume in escrow, active counts, API latency, and CPU/Memory usage
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.LedgerMetrics"];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending settlements
         * @description Retrieve all active settlement payment instructions awaiting Central Bank stablecoin release execution
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.EscrowSettlement"][];
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/{settlementID}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Settle pending payment
         * @description Central Bank settles the payout instruction, releasing stablecoins to the target recipient and marking it completed
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Settlement ID */
                    settlementID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description settlement failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List simulated wallets
         * @description Retrieve mock/simulated wallet balances for Central Bank, Depositor, Beneficiary, and Mediator in dev perimeters
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ledger.Wallet"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/milestone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Oracle webhook callback
         * @description External webhook receiver for oracle providers to sign off milestone target conditions
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Oracle Webhook Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.OracleWebhookRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description trigger rejected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api.AmendDraftRequest": {
            amount?: number;
            currency?: string;
            metadata?: Record<string, never>;
            summary?: string;
            terms?: Record<string, never>;
        };
        "api.CreateInvitationRequest": {
            amount?: number;
            assetId?: string;
            assetType?: string;
            conditionDescription?: string;
            conditionType?: string;
            /** @description ImportExport, RealEstate, etc. */
            contractType?: string;
            currency?: string;
            disputeWindowDays?: number;
            evidenceRequired?: string;
            expiryDate?: string;
            gracePeriodDays?: number;
            inviteeEmail?: string;
            /** @description Depositor or Beneficiary */
            inviteeRole?: string;
            inviteeType?: string;
        };
        "api.DiscoverAuthRequest": {
            email?: string;
        };
        "api.FundEscrowRequest": {
            custodyRef?: string;
            holdingCid?: string;
        };
        "api.OracleWebhookRequest": {
            asymmetric?: boolean;
            escrowId?: string;
            event?: string;
            milestoneIndex?: number;
            oracleProvider?: string;
            signature?: string;
        };
        "api.ProposeEscrowRequest": {
            amount?: number;
            assetId?: string;
            assetType?: string;
            beneficiary?: string;
            conditionDescription?: string;
            conditionType?: string;
            currency?: string;
            disputeWindowDays?: number;
            evidenceRequired?: string;
            expiryDate?: string;
            gracePeriodDays?: number;
            mediator?: string;
            payload?: {
                [key: string]: unknown;
            };
            schemaUrl?: string;
        };
        "api.ProposeSettlementRequest": {
            beneficiaryPayment?: number;
            depositorReturn?: number;
            mediatorFee?: number;
            settlementType?: string;
        };
        "api.SaveConfigRequest": {
            key?: string;
            value?: Record<string, never>;
        };
        "api.SaveDraftRequest": {
            amount?: number;
            beneficiaryEmail?: string;
            contractType?: string;
            currency?: string;
            metadata?: Record<string, never>;
            terms?: Record<string, never>;
        };
        "api.VerifyWalletRequest": {
            assumedRole?: string;
            damlPartyId?: string;
            nonce?: string;
            publicKey?: string;
            signature?: string;
        };
        "ledger.ActivityPoint": {
            count?: number;
            date?: string;
        };
        "ledger.Asset": {
            /** @example 0 */
            amount?: string;
            assetId?: string;
            assetType?: string;
            currency?: string;
            custodyRef?: string;
            holdingCid?: string;
        };
        "ledger.EscrowContract": {
            agreementUrl?: string;
            asset?: components["schemas"]["ledger.Asset"];
            beneficiary?: string;
            beneficiaryAccepted?: boolean;
            currentMilestoneIndex?: number;
            depositor?: string;
            depositorAccepted?: boolean;
            id?: string;
            issuer?: string;
            mediator?: string;
            metadata?: string;
            state?: string;
            terms?: components["schemas"]["ledger.EscrowTerms"];
        };
        "ledger.EscrowInvitation": {
            asset?: components["schemas"]["ledger.Asset"];
            contractType?: string;
            id?: string;
            inviteeEmail?: string;
            /** @description Depositor or Beneficiary */
            inviteeRole?: string;
            inviter?: string;
            issuer?: string;
            mediator?: string;
            terms?: components["schemas"]["ledger.EscrowTerms"];
            tokenHash?: string;
        };
        "ledger.EscrowProposal": {
            asset?: components["schemas"]["ledger.Asset"];
            beneficiary?: string;
            depositor?: string;
            id?: string;
            issuer?: string;
            mediator?: string;
            metadata?: string;
            terms?: components["schemas"]["ledger.EscrowTerms"];
        };
        "ledger.EscrowSettlement": {
            amount?: number;
            currency?: string;
            escrowId?: string;
            id?: string;
            issuer?: string;
            recipient?: string;
            settlement?: components["schemas"]["ledger.SettlementTerms"];
            state?: string;
            status?: string;
        };
        "ledger.EscrowTerms": {
            conditionDescription?: string;
            conditionType?: string;
            /** @example 0 */
            disputeWindowDays?: string;
            evidenceRequired?: string;
            expiryDate?: string;
            /** @example 0 */
            gracePeriodDays?: string;
            /** @example 0 */
            maxAmount?: string;
            /** @example 0 */
            minAmount?: string;
            /** @description Simplified for JSON */
            partialSchedule?: string[];
        };
        "ledger.HealthResponse": {
            cpuUsage?: number;
            goroutines?: number;
            memoryUsage?: number;
            services?: {
                [key: string]: components["schemas"]["ledger.ServiceHealth"];
            };
            startTime?: string;
            status?: string;
            uptime?: string;
            version?: string;
        };
        "ledger.LedgerHealth": {
            activeContracts?: number;
            commandSuccessRate?: number;
            identitiesAllocated?: number;
            tps?: number;
        };
        "ledger.LedgerMetrics": {
            activeEscrows?: number;
            activityHistory?: components["schemas"]["ledger.ActivityPoint"][];
            avgTimeToSettle?: string;
            bottleneckStage?: string;
            disputedEscrows?: number;
            ledgerHealth?: components["schemas"]["ledger.LedgerHealth"];
            settledVolume?: number;
            /** @description ms */
            stageLatencies?: {
                [key: string]: number;
            };
            /** @description percentage */
            successRate?: number;
            systemPerformance?: components["schemas"]["ledger.SystemPerformance"];
            totalActiveEscrows?: number;
            totalEscrows?: number;
            totalValueInEscrow?: number;
            tpsHistory?: components["schemas"]["ledger.ActivityPoint"][];
        };
        "ledger.ServiceHealth": {
            latencyMs?: number;
            message?: string;
            /** @description UP, DOWN, DEGRADED */
            status?: string;
        };
        "ledger.SettlementTerms": {
            /** @example 0 */
            beneficiaryPayment?: string;
            /** @example 0 */
            depositorReturn?: string;
            /** @example 0 */
            mediatorFee?: string;
            settlementType?: string;
        };
        "ledger.SystemPerformance": {
            apiLatencyMs?: number;
            cpuUsage?: number;
            memoryUsage?: number;
            p95LatencyMs?: number;
            p99LatencyMs?: number;
            uptime?: string;
        };
        "ledger.UserIdentity": {
            affiliation?: string;
            damlPartyId?: string;
            damlUserId?: string;
            displayName?: string;
            email?: string;
            /** @description PENDING, VERIFIED, REJECTED */
            kycStatus?: string;
            oktaSub?: string;
            organization?: string;
            physicalAddress?: string;
            /** @description Depositor, Beneficiary, Mediator */
            role?: string;
            title?: string;
        };
        "ledger.Wallet": {
            balance?: number;
            currency?: string;
            id?: string;
            owner?: string;
        };
        "services.DraftEscrow": {
            amount?: number;
            approvals?: string[];
            beneficiaryEmail?: string;
            beneficiaryId?: string;
            changeSummary?: string;
            /** @description ImportExport, RealEstate, Grants, Corporate */
            contractType?: string;
            createdAt?: string;
            currency?: string;
            depositorId?: string;
            id?: string;
            initiatorId?: string;
            initiatorRole?: string;
            invitationCode?: string;
            mediatorId?: string;
            metadata?: Record<string, never>;
            proposerId?: string;
            rootId?: string;
            /** @description DRAFT, CLAIMED, NEGOTIATION, RATIFIED, PROMOTED */
            status?: string;
            terms?: Record<string, never>;
            version?: number;
        };
        "services.EscrowLifecycleMetadata": {
            avgTimeToComplete?: string;
            currentState?: string;
            escrowId?: string;
            steps?: components["schemas"]["services.LifecycleStep"][];
            timeInCurrent?: string;
        };
        "services.IngestResult": {
            contentHash?: string;
            contractType?: string;
            extracted?: Record<string, never>;
            storageUri?: string;
            /** @description Merged and validated draft */
            suggested?: Record<string, never>;
            warnings?: string[];
        };
        "services.LifecycleStep": {
            actionBy?: string;
            description?: string;
            state?: string;
            /** @description COMPLETED, CURRENT, PENDING */
            status?: string;
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
