/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/escrows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new escrow contract
         * @description Initiate a new escrow agreement between buyer and seller
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Escrow Creation Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.CreateEscrowRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.EscrowResponse"];
                    };
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get escrow details by ID
         * @description Retrieve information about a specific escrow contract
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.EscrowResponse"];
                    };
                };
                /** @description escrow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refund funds to the buyer
         * @description Cancel escrow and return funds (requires mediator)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description refund failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release funds for the current milestone
         * @description Approve and release funds for the active milestone
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description release failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a disputed escrow
         * @description Mediator resolve dispute by splitting payout
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Escrow ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Dispute Resolution Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.ResolveDisputeRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description resolution failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all pending settlements
         * @description Retrieve a list of pending settlement obligations
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.SettlementResponse"][];
                    };
                };
                /** @description internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/{id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize a pending settlement
         * @description Issuer (Central Bank) settles the obligation and releases stablecoins
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Settlement ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description settlement failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api.CreateEscrowRequest": {
            /** @example 100 */
            amount?: number;
            /** @example Buyer */
            buyer?: string;
            /** @example USD */
            currency?: string;
            /** @example Payment for goods */
            description?: string;
            milestones?: components["schemas"]["ledger.Milestone"][];
            /** @example Seller */
            seller?: string;
        };
        "api.EscrowResponse": {
            amount?: number;
            buyer?: string;
            currency?: string;
            currentMilestoneIndex?: number;
            id?: string;
            milestones?: components["schemas"]["ledger.Milestone"][];
            seller?: string;
            state?: string;
        };
        "api.ResolveDisputeRequest": {
            /** @example 50 */
            payoutToBuyer?: number;
            /** @example 50 */
            payoutToSeller?: number;
        };
        "api.SettlementResponse": {
            amount?: number;
            currency?: string;
            id?: string;
            issuer?: string;
            recipient?: string;
            status?: string;
        };
        "ledger.Milestone": {
            amount?: number;
            completed?: boolean;
            label?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
