server:
  port: 8081

ledger:
  host: "localhost"
  port: 7575
  packages:
    implementation: "stablecoin-escrow"
    interfaces: "stablecoin-escrow-interfaces"
  parties:
    issuer: "CentralBank"
    depositor: "Depositor"
    beneficiary: "Beneficiary"
    mediator: "EscrowMediator"

userConfig:
  dsn: "postgres://escrow:escrow@localhost:5432/user_config?sslmode=disable"

auth:
  issuer: "https://integrator-6277421.okta.com/oauth2/aus11kvijsbutv9dC698"
  clientId: "0oa11kvi7mxaHbQaV698"
  audience: "daml-escrow"

oracle:
  webhookSecret: "development-secret-key"
