server:
  port: 8081

ledger:
  host: "127.0.0.1"
  port: 7575
  nodes:
    bank:
      host: "127.0.0.1"
      port: 7575
    buyer:
      host: "127.0.0.1"
      port: 7576
    seller:
      host: "127.0.0.1"
      port: 7577
  packages:
    implementation: "stablecoin-escrow"
    interfaces: "stablecoin-escrow-interfaces"
  parties:
    issuer: "CentralBank"
    buyer: "Buyer"
    seller: "Seller"
    mediator: "EscrowMediator"

userConfig:
  dsn: "postgres://escrow:escrow@127.0.0.1:5432/user_config?sslmode=disable"

auth:
  issuer: "https://integrator-6277421.okta.com/oauth2/aus11kvijsbutv9dC698"
  clientId: "0oa11kvi7mxaHbQaV698"
  audience: "daml-escrow"

oracle:
  webhookSecret: "development-secret-key"
