canton {
  participants {
    sandbox {
      storage {
        type = memory
      }
      admin-api {
        port = 6866
        address = 0.0.0.0
      }
      ledger-api {
        port = 6865
        address = 0.0.0.0
      }
      http-ledger-api {
        port = 7575
        address = 0.0.0.0
      }
    }
  }
  synchronizers {
    local-sync {
      storage {
        type = memory
      }
      admin-api {
        port = 6867
        address = 0.0.0.0
      }
      public-api {
        port = 6868
        address = 0.0.0.0
      }
    }
  }
}
