// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/escrows": {
            "post": {
                "description": "Initiate a new escrow agreement between buyer and seller",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "escrows"
                ],
                "summary": "Create a new escrow contract",
                "parameters": [
                    {
                        "description": "Escrow Creation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateEscrowRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.EscrowResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/escrows/{id}": {
            "get": {
                "description": "Retrieve information about a specific escrow contract",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "escrows"
                ],
                "summary": "Get escrow details by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Escrow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.EscrowResponse"
                        }
                    },
                    "404": {
                        "description": "escrow not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/escrows/{id}/refund": {
            "post": {
                "description": "Cancel escrow and return funds (requires mediator)",
                "tags": [
                    "escrows"
                ],
                "summary": "Refund funds to the buyer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Escrow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "refund failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/escrows/{id}/release": {
            "post": {
                "description": "Approve and release funds for the active milestone",
                "tags": [
                    "escrows"
                ],
                "summary": "Release funds for the current milestone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Escrow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "release failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateEscrowRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 100
                },
                "buyer": {
                    "type": "string",
                    "example": "Buyer"
                },
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "description": {
                    "type": "string",
                    "example": "Payment for goods"
                },
                "milestones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ledger.Milestone"
                    }
                },
                "seller": {
                    "type": "string",
                    "example": "Seller"
                }
            }
        },
        "api.EscrowResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "buyer": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "currentMilestoneIndex": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "milestones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ledger.Milestone"
                    }
                },
                "seller": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "ledger.Milestone": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "completed": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Stablecoin Escrow API",
	Description:      "API for managing privacy-preserving stablecoin escrows on DAML.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
